services:

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "5000:5000"
    environment:
      - USER=http://user-service:5001
      - INVOICE=http://invoice-service:5002
      - SUB=http://subscription-service:5003
      - PAYMENT=http://payment-service:5006
      - AI=http://ai-service:5005
    depends_on:
      - user-service
      - invoice-service
      - subscription-service
      - payment-service
      - ai-service

  user-service:
    build: ./backend/user-service
    ports:
      - "5001:5001"
    env_file:
      - ./backend/user-service/.env

  invoice-service:
    build: ./backend/invoice-service
    ports:
      - "5002:5002"
    env_file:
      - ./backend/invoice-service/.env

  subscription-service:
    build: ./backend/subscription-service
    ports:
      - "5003:5003"
    env_file:
      - ./backend/subscription-service/.env

  payment-service:
    build: ./backend/payment-service
    ports:
      - "5006:5006"
    env_file:
      - ./backend/payment-service/.env

  ai-service:
    build: ./backend/ai-service
    ports:
      - "5005:5005"
    env_file:
      - ./backend/ai-service/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway