services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - invoice-service
      - subscription-service
      - payment-service
      - ai-service
    restart: always

  user-service:
    build: ./backend/user-service
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    restart: always

  invoice-service:
    build: ./backend/invoice-service
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    restart: always

  subscription-service:
    build: ./backend/subscription-service
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
    restart: always

  payment-service:
    build: ./backend/payment-service
    ports:
      - "5004:5004"
    restart: always

  ai-service:
    build: ./backend/ai-service
    ports:
      - "5005:5005"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway
    restart: always